### ISSUE TITLE
Error reading Merge Order file

### ISSUE THREAD

**Issue by hhopp** [nolanlab/spade#102]
Hello,

I got Cytospade to work, and was able to edit FlowCore so that it could read exported FlowJo files. 
I read that in order to get the Attribute Color and the biaxial plot to work in Cytospade, you had to delete the layout.table before opening the output in Cytoscape. 
I did this. But now, when I open an output folder in cytoscape, I get this error:

Error reading Merge Order file: Merge order file is corrupted. Line number: 2 in file:merge_order.txt

It is always the same line, no matter what output folder I look at. 

When I look at the trees Cytospade, and highlight certain branches that look like they are from the same cell population, they appear to be scattered all around the biaxial plot. I was wondering if this merge order file error corruption had anything to do with this.

How do I fix this?

Thank you.

**Comment by zbjornson** [comment]
Sorry for the lack of response. We're not the Cytoscape plugin anymore unfortunately.
