### ISSUE TITLE
Cannot create iterator

### ISSUE THREAD

**Issue by ever4cyth** [nolanlab/spade#104]
Follow exactly the steps in example usage

> SPADE.driver("Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs", out_dir="output", cluster_cols=markers, panels=PANELS, transforms=flowCore::arcsinhTransform(a=0, b=0.2), layout=SPADE.layout.arch, downsampling_target_percent=0.1, downsampling_target_number=NULL, downsampling_target_pctile=NULL, downsampling_exclude_pctile=0.01, k=200, clustering_samples=50000)
Downsampling file: Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs
  Estimated downsampling-I progress:  0% ...
  Estimated downsampling-I progress: 100% ...
Targeting 9048 events for output/Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs.density.fcs
Clustering files...
Upsampling file: output/Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs.density.fcs
Error in .Call("R_igraph_get_shortest_paths", graph, as.igraph.vs(graph,  : 
  At iterators.c:759 : Cannot create iterator, invalid vertex id, Invalid vertex id
In addition: Warning messages:
1: In write.FCS(out_frame, outfilename) :
  'write.FCS' is not fully tested and should be considered as experimental.
2: In write.FCS(out_frame, outfilename) :
  'write.FCS' is not fully tested and should be considered as experimental.
3: In write.FCS(ff, outfilename) :
  'write.FCS' is not fully tested and should be considered as experimental.
4: In write.FCS(out_frame, outfilename) :
  'write.FCS' is not fully tested and should be considered as experimental.

**Comment by ustervbo** [comment]
I have the exact same experience. I have Cytoscape 2.8.3 installed and my sessionInfo() looks like this:

R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] spade_1.14.0         Rclusterpp_0.2.3     RcppEigen_0.3.2.3.0  Rcpp_0.11.3          igraph_0.7.1         BiocInstaller_1.16.1

loaded via a namespace (and not attached):
 [1] Biobase_2.26.0      BiocGenerics_0.12.1 cluster_1.15.3      corpcor_1.6.7       DEoptimR_1.0-2      flowCore_1.32.2    
 [7] graph_1.44.1        grid_3.1.2          lattice_0.20-29     Matrix_1.1-5        mvtnorm_1.0-2       parallel_3.1.2     
[13] pcaPP_1.9-60        robustbase_0.92-3   rrcov_1.3-8         stats4_3.1.2        tools_3.1.2

**Comment by dm319** [comment]
I'm having the same issue.  Using 64-bit Ubuntu 14.04 installation with R version 3.2.2, and followed the instructions on [github](https://github.com/nolanlab/spade/wiki/GettingStarted)/[bioconductor](http://bioconductor.org/packages/release/bioc/html/spade.html) to install the package.  I can load the library with library(spade).

I then followed the [example usage](https://github.com/nolanlab/spade/wiki/Example-Usage), but this error is generated:

> SPADE.driver("Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs", out_dir="output", cluster_cols=markers, panels=PANELS, transforms=flowCore::arcsinhTransform(a=0, b=0.2), layout=SPADE.layout.arch, downsampling_target_percent=0.1, downsampling_target_number=NULL, downsampling_target_pctile=NULL, downsampling_exclude_pctile=0.01, k=200, clustering_samples=50000)
Downsampling file: Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs
  Estimated downsampling-I progress:  0% ...
  Estimated downsampling-I progress: 100% ...
Targeting 9048 events for output/Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs.density.fcs
Clustering files...
Upsampling file: output/Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs.density.fcs
Error in .Call("R_igraph_get_shortest_paths", graph, as.igraph.vs(graph,  : 
  At iterators.c:759 : Cannot create iterator, invalid vertex id, Invalid vertex id
In addition: Warning messages:
1: In write.FCS(out_frame, outfilename) :
  'write.FCS' is not fully tested and should be considered as experimental.
2: In write.FCS(out_frame, outfilename) :
  'write.FCS' is not fully tested and should be considered as experimental.
3: In write.FCS(ff, outfilename) :
  'write.FCS' is not fully tested and should be considered as experimental.
4: In write.FCS(out_frame, outfilename) :
  'write.FCS' is not fully tested and should be considered as experimental.

**Comment by MoSyCH** [comment]
Hi,

I also do have the exact same issue. Using Windows 7 with R 64bits version 3.2.2, Cytoscape v2.8.3 and followed the instructions on github/bioconductor to install the package v1.18.0. Did someone found a solution ?
Thanks

**Comment by dm319** [comment]
So not just a linux issue.  Is Zack Bjornson able to look into this at all?  I'd really like to get this working!

**Comment by MoSyCH** [comment]
I finally went for matlab, instead of R, using SPADE v3.0.. SPADE runs perfectly with matlab R2012a.

I think that the error on R is due to version of the package "igraph" called by "spade" package or to the version of R itself. As I am very new to R, so I prefered to change for something I know how to use, matlab. You can also try SPADE with FlowJo directly but it also uses R so I am not sure if it is going to work.

Well... may be if you have some skills with R try to change for the different versions of igraph (igraph0 won't work). Else playing with the versions of R could help also.

Hope it helps.

**Comment by dm319** [comment]
That's good to know, I understand Prof Qui maintains that other version which runs on matlab.  We have a discount on matlab, so might give that a try, but I'm more familiar with R, so would rather get that working if I can.

**Comment by SamGG** [comment]
I looked into the code. I feel the problem is in the "annotation/graph" code. The get.shortest.paths now outputs a list whose vpath slot is the awaited part. It seems that igraph may be no more 0-indexed. I will look into in January if nobody else did it before.
But I feel that this will not allow SPADE to work with Cytoscape 2.8.3. If somebody has an opinion about that point, let me know.

**Comment by SamGG** [comment]
After a new look, I found that the SPADE layout is faulty due to igraph enhancements. Don't use the function `SPADE.layout.arch` until it is fixed. In the driver call, I used the default layout explicitly `layout=igraph::layout.kamada.kawai` instead of `layout=SPADE.layout.arch`. I get no error.
Then you can generate the tree, without error either.
Merry Christmas ;-)

**Comment by dm319** [comment]
Thanks SamGG - just in time too!  Will give this a go...  Merry Christmas to you all too.

**Comment by zbjornson** [comment]
Thanks @SamGG. Will happily merge that if you want to make a PR.

**Comment by dm319** [comment]
Hi there.  I've downloaded this project from github, and changed the line of code in the driver.R code as per samGG above.  I removed 'spade' using  remove.package' then used the 'install' command to install it from a local folder.  Unfortunately, I still have the issue.  Can anyone help?  Many thanks.

**Comment by SamGG** [comment]
Hi. Did you the layout in the function call? Could you post your script? Did you try a simple example?
Best.

**Comment by dm319** [comment]
Hi Sam, thanks for getting back to me.

My current system is ubuntu-mate 14.04 with R 3.2.3, spade 1.10.3, igraph 1.0.1.

Not sure I quite got your first question, but I assume related to the arch layout in the code?  My 'spade-master' is placed in ~/bin/spade-master.

I've edited the file ~/bin/spade-master/R/driver.R
line 484 now reads:
`SPADE.plot.trees <- function(graph, files, file_pattern="*anno.Rsave", out_dir=".", layout=igraph::layout.kamada.kawai, attr_pattern="percent|medians|fold|cvs", scale=NULL, pctile_color=c(0.02,0.98), normalize="global",size_scale_factor=1, edge.color="grey", bare=FALSE, palette="bluered") {`

I ran
`library(devtools)`
`install('~/bin/spade')`
and it seemed to install ok - here's the output:

```
Installing spade
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD  \
  INSTALL '/home/duncan/bin/spade-master'  \
  --library='/home/duncan/R/x86_64-pc-linux-gnu-library/3.2' --install-tests 

* installing *source* package ‘spade’ ...
checking for gcc... gcc -std=gnu99
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for gcc -std=gnu99 option to support OpenMP... -fopenmp
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking parallel/algorithm usability... yes
checking parallel/algorithm presence... yes
checking for parallel/algorithm... yes
configure: creating ./config.status
config.status: creating src/Makevars
** libs
make: Nothing to be done for `all'.
installing to /home/duncan/R/x86_64-pc-linux-gnu-library/3.2/spade/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
   ‘SPADE.Rnw’ 
** testing if installed package can be loaded
* DONE (spade)
```

My script is simply the getting started script:

`library('spade')`

output:
```
Loading required package: igraph

Attaching package: ‘igraph’

The following objects are masked from ‘package:stats’:

    decompose, spectrum

The following object is masked from ‘package:base’:

    union

Loading required package: Rclusterpp
Loading required package: Rcpp
Loading required package: RcppEigen
```

`markers <- c("Cd(110,111,112,114)","Cell_length","Dy(163.929)-Dual","Er(165.930)-Dual","Er(166.932)-Dual","Er(167.932)-Dual","Er(169.935)-Dual","Eu(150.919)-Dual","Eu(152.921)-Dual","Gd(155.922)-Dual","Gd(157.924)-Dual","Gd(159.927)-Dual","Ho(164.930)-Dual","In(114.903)-Dual","Ir(190.960)-Dual","La(138.906)-Dual","Lu(174.940)-Dual","Nd(141.907)-Dual","Nd(143.910)-Dual","Nd(144.912)-Dual","Nd(145.913)-Dual","Nd(147.916)-Dual","Nd(149.920)-Dual","Pr(140.907)-Dual","Sm(146.914)-Dual","Sm(151.919)-Dual","Sm(153.922)-Dual","Tb(158.925)-Dual","Tm(168.934)-Dual","Yb(170.936)-Dual","Yb(171.936)-Dual","Yb(173.938)-Dual","Yb(175.942)-Dual")`

`PANELS <- list(list(panel_files=c("Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs"), median_cols=NULL,reference_files=c("Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs"),fold_cols=c()))`
`SPADE.driver("Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs", out_dir="output", cluster_cols=markers, panels=PANELS, transforms=flowCore::arcsinhTransform(a=0, b=0.2), layout=SPADE.layout.arch, downsampling_target_percent=0.1, downsampling_target_number=NULL, downsampling_target_pctile=NULL, downsampling_exclude_pctile=0.01, k=200, clustering_samples=50000)`

And my error is:

```
Downsampling file: Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs
  Estimated downsampling-I progress:  0% ...
  Estimated downsampling-I progress: 100% ...
Targeting 9048 events for output/Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs.density.fcs
Clustering files...
Upsampling file: output/Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs.density.fcs
Error in .Call("R_igraph_get_shortest_paths", graph, as.igraph.vs(graph,  : 
  At iterators.c:759 : Cannot create iterator, invalid vertex id, Invalid vertex id
In addition: Warning messages:
1: In write.FCS(out_frame, outfilename) :
  'write.FCS' is not fully tested and should be considered as experimental.
2: In write.FCS(out_frame, outfilename) :
  'write.FCS' is not fully tested and should be considered as experimental.
3: In write.FCS(ff, outfilename) :
  'write.FCS' is not fully tested and should be considered as experimental.
4: In write.FCS(out_frame, outfilename) :
  'write.FCS' is not fully tested and should be considered as experimental.
```

Any help much appreciated!

**Comment by dm319** [comment]
Anyone with any ideas?  Maybe try an older version igraph?

**Comment by spholmes** [comment]
Sam's Xmas solution above worked for me:
`layout=igraph::layout.kamada.kawai instead of layout=SPADE.layout.arch.`

I have igraph version 1.0.1 and spade 1.18.2 and R version 3.2.3 (2015-12-10).

**Comment by SamGG** [comment]
@susan happy you succeeded. IMHO, the SPADE algorithm is one of the smarter algorithms I tried under R in the discovery field. The density reduction performs very well. That allows one finding very quite rare populations. The other brilliant point is that the high level clustering is let done by the expert instead of assuming an algorithm could perform better. Unfortunately, the CytoScape seems not be running anymore, and I don't know the current status of the Gephi plugin developpment.

@dm319 sorry for my late answer now. In fact you spent a lot of effort in modifying the code, which is not necessary IMHO. But it seems to me that you let the faulty parameter in the driver call `layout=SPADE.layout.arch,`. Susan succeeded in running the demo code while changing the layout call. I have just run the same code under my Windows laptop with the following libraries flowCore_1.36.9, spade_1.18.2, igraph_1.0.1, Rclusterpp_0.2.3, RcppEigen_0.3.2.8.1, Rcpp_0.12.3, rrcov_1.3-11, Biobase_2.30.0. Here is my call to the driver function:
```r
SPADE.driver(files="Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs", out_dir="output", cluster_cols=markers, panels=PANELS, transforms=flowCore::arcsinhTransform(a=0, b=0.2), layout=layout.kamada.kawai, downsampling_target_percent=0.1, downsampling_target_number=NULL, downsampling_target_pctile=NULL, downsampling_exclude_pctile=0.01, k=20, clustering_samples=5000)
```
Could you try it and let us know?

**Comment by dm319** [comment]
I am an idiot.  Will report back.

**Comment by dm319** [comment]
Ok, it works!  I will leave the source code alone in the future.  Although, speaking of which - spade seems to have been deprecated on bioconductor - it would be a shame for it to dropped, though I suppose it isn't too hard to install from here.

**Comment by spholmes** [comment]
Yes, it is deprecated because of the segmentation fault issue #115
<https://github.com/nolanlab/spade/issues/115>
which is linked to the Rclusterpp package not being up to date on CRAN,
where the default installer goes to get the package.



On Sun, Mar 13, 2016 at 2:02 PM, dm319 <notifications@github.com> wrote:

> Ok, it works! I will leave the source code alone in the future. Although,
> speaking of which - spade seems to have been deprecated on bioconductor -
> it would be a shame for it to dropped, though I suppose it isn't too hard
> to install from here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nolanlab/spade/issues/104#issuecomment-196053315>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by zbjornson** [comment]
I think I correctly fixed `SPADE.layout.arch` -- the example usage works correctly now. Please let me know if you have any problems.

As for the other comments -- I've updated the readme to show instructions for installing both Rclusterpp and SPADE from github, as we're no longer using bioconductor or CRAN.

**Comment by dm319** [comment]
Many thanks for fixing this Zach.

I'm really glad to see this unique piece of software maintained.  If I can get my programming skills up, I will try to help!

All best,
Duncan.

**Comment by SamGG** [comment]
Very good job Zach! You updated the SPADE layout better than my attempts.

I have just updated to spade_1.10.4 under Windows/R3.2.3 and succeeded in getting the PDFs.

Thanks for maintaining SPADE under R. The GUI was very helpful...

Although CRAN or BioConductor procedures may sound overwhelming, they provide usually an easy access for bench users who are not experienced in installing devtools for example. Susan, unless Nolan's lab get more human power, don't rely on CRAN and BioC for the current and next versions.

Best.

**Comment by zbjornson** [comment]
Glad to hear the fix works, thanks.

Resources permitting we might be able to resurrect a GUI, perhaps the HTML5/SVG GUI from several years ago. Will look at easier distribution as well...

**Comment by dm319** [comment]
An HTML5 GUI sounds great (says the linux person...)

**Comment by SamGG** [comment]
Meanwhile, could you point me to the source of the CytoSPADE that was working within Cytoscape 2.8.3 or 2.8.2? I think you already told about that, but I can't find it again. Hope you could help.

**Comment by zbjornson** [comment]
I think this JAR works, although that's after I attempted the igraph0/igraph update; you might have better luck with an older version. https://github.com/nolanlab/spade/raw/7a3fdd8db269df5c7f196b48bc1a73db273ce101/inst/tools/CytoSPADE.jar

The source is in another repository:
https://github.com/nolanlab/cytospade
The repository in sad shape after someone force-pushed irrelevant code to master and I have not repaired it yet. I believe this is this latest "working" source:
https://github.com/nolanlab/cytospade/tree/a911ebc908054b7e0cda733ea7785ef7e7cdef12

**Comment by SamGG** [comment]
I was so perplex during browsing the dev and Gephi branches that I asked you finally. Thanks a lot.
What is interesting in Cytobank implementation is the capability of creating many 2D plots. That allows to verify the spreading of events in many plots without the need of changing axes again and again. I think others here may have some interesting feedback also.
Best.
