### ISSUE TITLE
Cytospace2.8.3.dmg problem opening in OS X Yosemite

### ISSUE THREAD

**Issue by akhst7** [nolanlab/spade#105]
Hi, 

After clinking on the installer in a Cytospace2.8.3 disk image, I get an error message saying the installer app is damaged.  I am using OS X ProductVersion: 10.10 uildVersion:	14A389 in the mini with 16GB RAM.  

Thanks.

**Comment by zbjornson** [comment]
Sorry for the late response. This isn't a bug in spade/cytospade. Try downloading the installer again.
