### ISSUE TITLE
SPADE.driver issue

### ISSUE THREAD

**Issue by cguib** [nolanlab/spade#107]
Hi,

I'm trying now cytospade for the first time, following the sequence of your "example usage" page (https://github.com/nolanlab/spade/wiki/Example-Usage). When I reach the SPADE.driver stage I get the following error message: 
Error in if (length(files) == 1 && file.info(files)$isdir) { : 
  missing value where TRUE/FALSE needed

This also happens when I try to use your dataset (Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs).

Is there an additional file required?

best regards,

C.

**Comment by FlowLover** [comment]
Hi C,
Even I have been facing the same issue, could you solve it?

Regards,
F

**Comment by zbjornson** [comment]
Please provide your runSPADE.R script. This can be caused by things like a bad relative path or lack of permissions for R to access the specified path.

**Comment by FlowLover** [comment]
Hi Z,

Thanks for your prompt response. Here is the code:

> library(spade)
Loading required package: igraph
Loading required package: Rclusterpp
Loading required package: Rcpp
Loading required package: RcppEigen
> data_file_path = system.file(file.path("extdata","Panel1HC1.fcs"), package = "spade")
> data_file_path
[1] ""
> output_dir <- tempdir()
> transforms <- c('TLR2'=flowCore::arcsinhTransform(a=0, b=0.2),'TLR4'=flowCore::arcsinhTransform(a=0, b=0.2),'TLR5'=flowCore::arcsinhTransform(a=0, b=0.2),'CD3'=flowCore::arcsinhTransform(a=0, b=0.2),'CD19'=flowCore::arcsinhTransform(a=0, b=0.2),'CD66b'=flowCore::arcsinhTransform(a=0, b=0.2),'CD56'=flowCore::arcsinhTransform(a=0, b=0.2),'HLA-DR'=flowCore::arcsinhTransform(a=0, b=0.2),'CD14'=flowCore::arcsinhTransform(a=0, b=0.2),'CD16'=flowCore::arcsinhTransform(a=0, b=0.2)
+ )
> SPADE.driver(data_file_path, out_dir=output_dir, transforms=transforms, cluster_cols=c("TLR2","TLR4","TLR5","CD3","CD19","CD66b","CD56","HLA-DR","CD14","CD16"))
Error in if (length(files) == 1 && file.info(files)$isdir) { : 
  missing value where TRUE/FALSE needed

Regards,

F

**Comment by zbjornson** [comment]
@flowlover this isn't returning your file as you want it to:

````
data_file_path = system.file(file.path("extdata","Panel1HC1.fcs"), package = "spade")
````

Play around with that line in the R terminal... You probably need something more like "/extdata/Panel1HC1.fcs" without the two functions.

**Comment by FlowLover** [comment]
Hi Zach,

I tried as you suggested. But the error remains. Moreover, I get the same error message when I try with your dataset (Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs).

following the sequence of codes given at https://github.com/nolanlab/spade/wiki/Example-Usage.

I am sorry if it is an elementary error, I am quite new to R.

Thanks for your help,

Ratan

**Comment by zbjornson** [comment]
I added a more useful error message in https://github.com/nolanlab/spade/commit/5cecc21832a1d02e7895bfcaa3bca220c1ccc8e3, which will state if the specified file cannot be found.

I can only guess that you're specifying a file path pointing to a different part of your system. Try using an absolute path (e.g. "/extdata/Panel1HC1.fcs" or "/documents/Bendall_et_al..."). Let me know if you still have problems.
