### ISSUE TITLE
igraph cannot create iterator

### ISSUE THREAD

**Issue by studentofscience** [nolanlab/spade#108]
after executing the third line (exactly from example):

=============CODE USED==========
markers <- c("Cd(110,111,112,114)","Cell_length","Dy(163.929)-Dual","Er(165.930)-Dual","Er(166.932)-Dual","Er(167.932)-Dual","Er(169.935)-Dual","Eu(150.919)-Dual","Eu(152.921)-Dual","Gd(155.922)-Dual","Gd(157.924)-Dual","Gd(159.927)-Dual","Ho(164.930)-Dual","In(114.903)-Dual","Ir(190.960)-Dual","La(138.906)-Dual","Lu(174.940)-Dual","Nd(141.907)-Dual","Nd(143.910)-Dual","Nd(144.912)-Dual","Nd(145.913)-Dual","Nd(147.916)-Dual","Nd(149.920)-Dual","Pr(140.907)-Dual","Sm(146.914)-Dual","Sm(151.919)-Dual","Sm(153.922)-Dual","Tb(158.925)-Dual","Tm(168.934)-Dual","Yb(170.936)-Dual","Yb(171.936)-Dual","Yb(173.938)-Dual","Yb(175.942)-Dual")

PANELS <- list(list(panel_files=c("Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs"), median_cols=NULL,reference_files=c("Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs"),fold_cols=c()))

SPADE.driver("Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs", out_dir="output", cluster_cols=markers, panels=PANELS, transforms=flowCore::arcsinhTransform(a=0, b=0.2), layout=SPADE.layout.arch, downsampling_target_percent=0.1, downsampling_target_number=NULL, downsampling_target_pctile=NULL, downsampling_exclude_pctile=0.01, k=200, clustering_samples=50000)
=============END CODE USED==========

+++++++++++++++ERROR/OUTPUT+++++++++++++++
Downsampling file: Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs
  Estimated downsampling-I progress:  0% ...
  Estimated downsampling-I progress: 100% ...
Targeting 9048 events for output/Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs.density.fcs
Clustering files...
Upsampling file: output/Bendall_et_al_Science_2011_Marrow_1_SurfacePanel_Live_CD44pos_Singlets.fcs.density.fcs
Error in .Call("R_igraph_get_shortest_paths", graph, as.igraph.vs(graph,  : 
  At iterators.c:759 : Cannot create iterator, invalid vertex id, Invalid vertex id
In addition: Warning messages:
1: In write.FCS(out_frame, outfilename) :
  'write.FCS' is not fully tested and should be considered as experimental.
2: In write.FCS(out_frame, outfilename) :
  'write.FCS' is not fully tested and should be considered as experimental.
3: In write.FCS(ff, outfilename) :
  'write.FCS' is not fully tested and should be considered as experimental.
4: In write.FCS(out_frame, outfilename) :
  'write.FCS' is not fully tested and should be considered as experimental.
> layout <- read.table(file.path("output","layout.table"))
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'output/layout.table': No such file or directory

**Comment by zbjornson** [comment]
Duplicates #104
