### ISSUE TITLE
Which Cytoscape version to use with current version of spade R library?

### ISSUE THREAD

**Issue by SamGG** [nolanlab/spade#110]
Hi,

I tried 2.8.3 on Windows 7 and Linux Mint. Although computation are done within R, no way to use Cytoscape plugin to view and analyze the result. Any clue? Should I switch to Cytoscape 3.x?

Best

**Comment by zbjornson** [comment]
Hello,
We've essentially stopped supporting Cytoscape. Soon we're releasing a Gephi plugin with basic functionality for viewing SPADE trees. Meanwhile, you can import GML files in Cytoscape and explore a bit that way, or try the fully supported version in Cytobank (www.fluidigm.cytobank.org).
Best,
Zach

**Comment by SamGG** [comment]
Thanks for your answer Zach. I have already imported GML in Cytoscape and play around. That's good, but the plugin allowed density plot which was as very nice feature. I guess you mean that such a feature will not be ported to Gephi. I played also with Cytobank, but not all users would pay for it.
Apart from the visualisation/gating part, are the R codes stable and roughly the same as Cytobank ?
Best.

**Comment by zbjornson** [comment]
The plot will be ported, yes. The T test will likely not be ported.

The R code is stable and is the same used in Cytobank.

**Comment by SamGG** [comment]
Yeah, the plot is the major feature needed. Thanks.

**Comment by SamGG** [comment]
Yeah, the plot is the major feature needed. Thanks.
Let us know when a alpha/beta version is available for testing.
Best.
