### ISSUE TITLE
Error in Spade.driver: unused argument (downsampling_samples = DOWNSAMPLED_EVENTS)

### ISSUE THREAD

**Issue by labrett** [nolanlab/spade#112]
Hello,

I know this has been brought up before, but I am not aware of the solution. When using cytoscape 2.8.3, I get an error when trying to run the SPADE algorithm saying:

Error in SPADE.driver(FILE_TO_PROCESS, file_pattern = "*.fcs", out_dir = OUTPUT_DIR,  : 
  unused argument (downsampling_samples = DOWNSAMPLED_EVENTS)

I believe it was stated that this would be fixed in version 3, but when I use version 3 I get an error when installing SPADE through R:

SPADE.installPlugin("/Applications/Cytoscape_v3.0.0/")
Error in if (!file.exists(target_path) && !file.info(target_path)$isdir) { : 
missing value where TRUE/FALSE needed

How can I resolve this issue?

**Comment by zbjornson** [comment]
Hello,
Please see this answer: https://github.com/nolanlab/spade/issues/95#issuecomment-46481966
