### ISSUE TITLE
Can't cluster flow cytometry data on all channels 

### ISSUE THREAD

**Issue by Dawsondmg** [nolanlab/spade#114]
Not all of the fluorescence channels appear on the parameter selection box after I select calculate SPADE in FlowJo.  Is there some way to fix this? Also, if I'm analyzing a SPADE tree in Cytoscape, is it possible to gate on the actual plot within Cytoscape? 

Thanks!

**Comment by zbjornson** [comment]
Hello,

Please contact FlowJo support about that question. They integrated our open-source package and we don't know if they modified it in a way that would cause this. However, note that only channels that are common to all of your FCS files can be used for clustering. Perhaps that is what you're encountering.

In Cytoscape, you cannot gate on the plot. Selecting nodes shows the events from those nodes in the plot (opposite of what you're asking).

Best,
Zach

**Comment by Dawsondmg** [comment]
Thanks Zach! I'll contact FlowJo. Also, is it correct that one can circumvent FlowJo by using R and Cytospade to generate the output files for analysis in Cytoscape?

Thanks again,
Dawson
________________________________

**Comment by zbjornson** [comment]
Hi Dawson,
Our Cytoscape plugin is currently broken. If you are comfortable with the basics of R, you can run SPADE entirely from R. The [tutorial](https://github.com/nolanlab/spade/wiki/Example-Usage) walks through most of the steps. The final alternative is using Cytobank. It is a paid feature but I think free 30-day trials are available.
Zach
