### ISSUE TITLE
How can I find which node(cluster) a certain cell in cytometry data is assigned to?

### ISSUE THREAD

**Issue by zzf2015** [nolanlab/spade#116]
I used SPADE to analyze cytometry data and successfully got the SPADE trees in PDF form. However, I want to know the exact assignment of each cluster (as I described in title). I find the "cluster" column added to the original fcs file after running SPADE and I guess I can find what I want in that column. But  I cannot see any connection between the data in "cluster" column and the nodes(clusters) in SPADE trees. Any help is appreciated!
Many thanks!
Steven

**Comment by zbjornson** [comment]
I don't quite follow what you're trying to do. The cluster column is the ID of the cluster to which the cell is assigned, yes. The PDFs don't display the IDs of the cluster though. The GML files list the IDs and the x,y coordinates of the nodes. Does that get you closer to what you want?

**Comment by zzf2015** [comment]
Thanks for your quick reply.
I got 198 clusters(nodes). And the IDs of nodes you mentioned are supposed to be numbers from I to 198, am I right?
But the numbers in "cluster" column are not numbers from 1 to 198. For example, the first three number in the "cluster" column are 580.168, 1464.08 and 3.17868. And I don't know what do those numbers mean.

**Comment by zbjornson** [comment]
That's right (although I forget, one version was 0-indexed, another was 1-indexed, so it might be 0 to 197). The clusters should be integers. Can you please triple check that you're looking at the `<originalName>.cluster.fcs` file, and the right column within that?

**Comment by SamGG** [comment]
Hi,
I never did it, but may be the software you are using is scaling the cluster id. If you display that column, I think you get a limited number of  discrete (separated) levels, one for each cluster.

**Comment by zbjornson** [comment]
Closing due to age. Please feel free to re-open if you have any more questions.
