### ISSUE TITLE
Problem with SPADE.installPlugin

### ISSUE THREAD

**Issue by zji90** [nolanlab/spade#117]
Hi,
My system is OSX. I have installed both Cytoscape (v3.2.1) and the spade R package. However, when I was running SPADE.installPlugin("/Applications/Cytoscape_v3.2.1"), it says:
Error in if (!file.exists(target_path) && !file.info(target_path)$isdir) { : 
  missing value where TRUE/FALSE needed
It seems that there is no "plugins" folder under "Cytoscape" folder. Does anyone know how to fix it? Thanks!

**Comment by zbjornson** [comment]
Sorry for the slow response. The SPADE plugin is not compatible with Cytoscape 3.x (see #59).
