### ISSUE TITLE
How do I analyze SPADE output with Cytoscape?

### ISSUE THREAD

**Issue by sudinb** [nolanlab/spade#120]
Hi,
I am a new user of CytoSPADE. I have been able to install the R package and the Cytoscape plugin, and ran it on a test set of files and produced the output. However, I am having trouble analyzing the SPADE output with Cytoscape. I have watched Screencast Tutorial Part 5, but the interface shown there does not match that of the current version. For example, I am not getting the tree structure when I open my "basal" file, and can't choose a Coloring Attribute. Also, how do I visualize the median changes of a particular marker over my datasets?

- Thanks,
Sudin Bhattacharya

Sudin Bhattacharya
Assistant Professor
Institute for Integrative Toxicology
Michigan State University
Food Safety and Toxicology Building
1129 Farm Ln Room 324 
East Lansing MI 48824
517.884.6952 | sbhattac@msu.edu
http://iit.msu.edu/faculty/bhattacharya_sudin.html

**Comment by zbjornson** [comment]
Hi Sudin, sorry for the delay. We're not supporting the Cytoscape plugin much anymore unfortunately. Your SPADE run should have created a folder called `PDFs` that contains trees for every marker and metric. Fold changes requires that you have setup "panels" (groups of files within which one or more files is marked the basal file) in the runSPADE.R file -- have you done this? If not I will dig up an example of what that needs to look like.

There is a maintained/supported SPADE viewer in Cytobank that you could check out as well.
