### ISSUE TITLE
Is SPADE about to be retired?

### ISSUE THREAD

**Issue by oneillkza** [nolanlab/spade#123]
Hi there

I've been considering using SPADE, but noticed that in the past week or so it's failed the nightly builds on Bioconductor and been deprecated from future releases, and that the Cytoscape plugin has been removed from the code base. 

Are there plans to make SPADE a working package again?

**Comment by zbjornson** [comment]
The SPADE R package works and will continue to be maintained here, and we support distribution of SPADE via GitHub (see new readme) instead of Bioconductor. The Cytoscape plugin is no longer supported, but if we have more resources we'll resurrect the HTML5 viewer. Cytobank also provides a viewer.

**Comment by oneillkza** [comment]
Thanks, good to know!

Right now it seems not to build on OSX, and I note that the BioC version was throwing a segfault on one of the examples. I'll see if I can get devtools to work and retry (which may, hopefully fix the build issue), and if that doesn't I'll put together a more descriptive issue.

**Comment by anaraserikbek** [comment]
Hello everyone, 
Zach Bjorson, what did you mean by "cytobank also provides a viewer?". Are we still able to use cytobank to do SPADE analysis? I've gone through cytobank and seems they only have descriptions on how to use SPADE, etc. but not the actual workspace where one can uploadd an .fcs file for analysis? 
Also, are there any other vignettes on using SPADE in R except the one on SPADE's bioconductor space? 
Thank you

**Comment by zbjornson** [comment]
@anaraserikbek It sounds like you were in the documentation site and not in actual Cytobank. If you go here: https://premium.cytobank.org/cytobank/login you can register and get a 30 day free trial. The free versions don't include SPADE.
