### ISSUE TITLE
SPADE vignettes

### ISSUE THREAD

**Issue by anaraserikbek** [nolanlab/spade#125]
Hello everyone, 
Are there any other SPADE package vignettes for R users except the one provided in Bioconductor website? (http://bioconductor.org/packages/release/bioc/vignettes/spade/inst/doc/SPADE.pdf)
I'm a new user to R & would be happy to read any other additional information with examples of using packages on SPADE. 
Also, is it still possible to invoke CytoSPADE through Cytoscape's plugin menu? (to use it through R)?

**Comment by zbjornson** [comment]
That is the only actual vignette. We do have an example usage in the [wiki](https://github.com/nolanlab/spade/wiki/Example-Usage).

We don't support the Cytoscape plugin anymore. The current workflow is to edit the runSPADE.R file (which corresponds to the steps in the wiki), run the script with R, and then look at the output PDFs. Cytobank has a SPADE tool in their premium versions as well.
