### ISSUE TITLE
SPADE.driver function 

### ISSUE THREAD

**Issue by anaraserikbek** [nolanlab/spade#126]
When downsampling & generating the SPADE tree through the function SPADE.driver, in the parameter cluster_cols, in the vignette you specify cluster_cols=c("marker1","marker2"), and I tried to specify the marker names, the channel names or the column numbers for the markers that I'm interested in making the tree from, and in any case I'm getting the Error: **Error in SPADE.addDensityToFCS(f, f_density, cols = cluster_cols, comp = comp,  : 
  Invalid column specifier** 
The methods I have tried to use: 
1. cluster_cols=c(16,17)
2. cluster_cols=c("CD3","CD4")
3. cluster_cols=c("channel name1","channel name2") 
I cannot run for all markers, even though it is working & I'm receiving the results, the program is taking too long to process for all the cells/markers.

**Comment by SamGG** [comment]
Please do show the markers of one of the FCS you query in order to get a better view of what could go wrong.

**Comment by zbjornson** [comment]
The `cluster_cols` should be the channel name (as opposed to the reagent name). If you can peek inside your FCS file with a text editor, the values will be those after the $PnN keywords (e.g. "FITC-A" in `/$P1N/FITC-A/`).

If your FCS file is large and tricky to open with a text editor, you can use `head -n 1 <path/to/file.fcs>` in a terminal, or use a flow cytometry analysis tool to see what the channel names are.

**Comment by zbjornson** [comment]
@anaraserikbek Please comment if you still need assistance with this issue and I will re-open it.

**Comment by anaraserikbek** [comment]
the issue is solved, thank you for your help!
