### ISSUE TITLE
SPADE.driver

### ISSUE THREAD

**Issue by gdreiman1** [nolanlab/spade#127]
I'm following the code listed in the Nature Methods Paper, as I am trying to learn how to use Spade for analyzing  non-cytometry data.  However, when I try to run SPADE.driver I get the following error message: 
SPADE.driver(files='input_dir', out_dir='output_dir', transforms='transforms')
Error in if (length(files) == 1 && file.info(files)$isdir) { : 
  missing value where TRUE/FALSE needed

Can somebody help me understand this? I am relatively new to R.

**Comment by zbjornson** [comment]
That probably means that your input directory isn't actually being found.

Is this the actual line that you're running:

> `SPADE.driver(files='input_dir', out_dir='output_dir', transforms='transforms')`

If so, that means that R will look for files in a folder named "input_dir" in your working directory (run `getwd()` to figure out your working dir).

Usually it's easier to use a full path name, starting from (windows) the drive letter, like C:/path/to/files or (mac/linux) the root, like /users/path/to/files.

**Comment by gdreiman1** [comment]
I had my working dir set to "input_dir", got it now. Thanks!
