### ISSUE TITLE
About runSPADE.R

### ISSUE THREAD

**Issue by monchin** [nolanlab/spade#142]
Hello,
I recently am interested in the visualization of high-dimensional data, and I found SPADE here. I haven't used R before, so I tested the example on example usage and I succeeded, although I still don't know the exact meaning of each pdf(lol). 
Then I thought maybe I could test the MNIST, so I dimensional-reduced the MNIST to 30-D, and turned it into .fcs, but when I would like to operate SPADE, an error occured "Panel files must be a subset of analysis files", the code is almost the same as the example:
```R
library(spade)
markers <- c("0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29")
PANELS<-list(list(panel_files=c("E:/dimension_reduction/data/MNIST/Output/X.fcs"), median_cols=NULL,reference_files=c("E:/dimension_reduction/data/MNIST/Output/X.fcs"),fold_cols=c()))
SPADE.driver("E:/dimension_reduction/data/MNIST/Output/X.fcs",out_dir="output",cluster_cols=markers,panels=PANELS,transforms=flowCore::arcsinhTransform(a=0, b=0.2), layout=SPADE.layout.arch, downsampling_target_percent=0.1, downsampling_target_number=NULL, downsampling_target_pctile=NULL, downsampling_exclude_pctile=0.01, k=200, clustering_samples=50000)
layout <- read.table(file.path("output","layout.table"))
mst <- read.graph(file.path("output","mst.gml"),format="gml")
SPADE.plot.trees(mst,"output",file_pattern="*fcs*Rsave",layout=as.matrix(layout),out_dir=file.path("output","pdf"),size_scale_factor=1.2)
```
 I googled this information and found [https://github.com/nolanlab/spade/issues/16](url), which says that "there is a disagreement between the files in the
folder you are analyzing, and the runSPADE.R file." 
So I looked for the runSPADE.R and found that it asks me to set something in it. Then I have these questions:
1. Do I need to set these things every time I'd like to run a new .fcs?
2. I don't quite know the meaning of the parameters to be set, for example, when I ran the example "Bendall", I didn't set FILE_TO_PROCESS, but it still worked. And I didn't find the CLUSTERING_MARKERS such as CD3(Cd114)Dd in the raw Bendall.fcs (I turned it to csv and didn't find these markers), so I even don't know how to set these parameters when I'd like to run a new data such as 30-D MNIST.
It would be appreciated if you can help me. 
Sincerely
Chuang

**Comment by zbjornson** [comment]
>  "Panel files must be a subset of analysis files"

That's a cryptic error; the values listed in `PANELS` should just be the file basename and not the full file paths, so:

```R
PANELS<-list(list(panel_files=c("X.fcs"), median_cols=NULL,reference_files=c("X.fcs"),fold_cols=c()))
```

> Do I need to set these things every time I'd like to run a new .fcs?

Yes, but note that SPADE was designed to analyze multiple FCS files at once...

> I didn't find the CLUSTERING_MARKERS such as CD3(Cd114)Dd in the raw Bendall.fcs 

I haven't looked at `runSPADE.R` in several years, but I think the values in there are from a dataset that isn't in this repo. The example in the wiki (https://github.com/nolanlab/spade/wiki/Example-Usage) shows markers that correspond to the `$PnN` values in the FCS file posted on that page if you want to compare there.

You probably also want to set `transforms=flowCore::linearTransform(a=1, b=0)` unless you want to apply ArcSinh[x/5] to your values.

---

I don't think SPADE lends itself well to the MNIST database, but I'm interested to hear if you find something useful from it.

**Comment by monchin** [comment]
Thank you for your reply! But now I found a new problem that the layout of the graph is too strange. The layout of the example Bendall.fcs is like: ![bendall_layout](https://user-images.githubusercontent.com/18521800/39077046-ac7d253c-4531-11e8-8b46-6141cd95e2b5.PNG),

 and I tried several times, but every time it generates a similar layout. I think it is too ugly so I looked the code of spade, and found in drive.R that it used `layout=igraph:::layout.kamada.kawai` as layout function, then it read the mst.gml as graph and layout the graph. So I found the mst.gml of Bendall.fcs, and use the same layout function to layout the graph and plot it, then I found that the layout is somewhat much better than the former: 
![layout_myself](https://user-images.githubusercontent.com/18521800/39077065-c35e12de-4531-11e8-87db-d6fec81586a8.png)
I'm very confused that the same data and the same layout function, why is the difference  so obvious between them?  what's the probable reason?
Thank you!

**Comment by zbjornson** [comment]
Those images didn't upload (or I don't have access -- you can copy and paste images directly into github comments), but the layout of an MST has no meaning (as long as the edge lengths are not representing any information, and as long as you didn't add any meaning by creating your own layout). Is that what you're asking about?

**Comment by monchin** [comment]
Hello, @zbjornson 
I send you an e-mail about the images and my questions. Thank you very much!

**Comment by monchin** [comment]
I have found the reason why the layout is that. It is because the example used "layout=SPADE.layout.arch" when the "SPADE.driver" function is called. SPADE.layout.arch can produce a stable layout when use the same data, but I don't that like the layout. If I don't declare "layout" parameter explicitly in "SPADE.driver" function, the default layout would be igraph:::layout.kamada.kawai, which would produce different layouts for the same data in different times, but the layout for me is good.
