### ISSUE TITLE
Problems producing PDFs

### ISSUE THREAD

**Issue by nbjorkstrom** [nolanlab/spade#67]
Hi,

Sorry to bother but I'm having some problems producing PDFs after rearranging my tree in Cytoscape using SPADE. After clicking on Produce PDFs I see the Generate PDFs window with the option to change node size scale factor. After that, nothing happens independently if I click on 'Generate PDFs' or on 'Next'. The original PDFs are still in the output/pdf/ folder and are not being replaced. Any thought on what I'm doing wrong?

Thanks,
Niklas

**Comment by zbjornson** [comment]
Closing this because we no longer support the Cytoscape plugin...
