### ISSUE TITLE
Error in spade.driver

### ISSUE THREAD

**Issue by Frekth** [nolanlab/spade#95]
Hi,
I am trying to analyse flow data generated from BD FACSDiva, but get the following error message:

Error in SPADE.driver(FILE_TO_PROCESS, file_pattern = "*.fcs", out_dir = OUTPUT_DIR,  : 
  unused argument (downsampling_samples = DOWNSAMPLED_EVENTS)
Execution halted 

Any input would be highly appreciated.

**Comment by zbjornson** [comment]
If anyone in this thread still has questions, please re-open or create a new issue. Thanks!
