### ISSUE TITLE
Mavericks build issue, forwarded from BioConductor

### ISSUE THREAD

**Issue by mlinderm** [nolanlab/spade#98]
Hi,

spade is failing to build on Mavericks in release and devel:

http://www.bioconductor.org/checkResults/release/bioc-LATEST/spade/morelia-buildsrc.html
http://www.bioconductor.org/checkResults/3.0/bioc-LATEST/spade/oaxaca-buildsrc.html

We've recently published a guide to pitfalls of using C++ on Mavericks:

http://www.bioconductor.org/developers/how-to/mavericks-howto/

Maybe it will help?

Can you have a look and try and fix this? Please let me know if you have any questions.

Thanks,
Dan

**Comment by zbjornson** [comment]
EOL'ing bioconductor distribution...
